apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-enrichment
spec:
  replicas: 2  # Run 2 instances of this service
  selector:
    matchLabels:
      app: data-enrichment
  template:
    metadata:
      labels:
        app: data-enrichment
    spec:
      containers:
        - name: data-enrichment
          image: my-docker-repo/data-enrichment:latest  # Docker image
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: data-enrichment-service
spec:
  selector:
    app: data-enrichment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Change to LoadBalancer for external access
